CREATE TABLE cycles (
 cycle_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE beamlines (
 beamline_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE btrs (
 btr_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE samples (
 sample_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE datasets (
 dataset_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 meta_id VARCHAR(500) NOT NULL UNIQUE,
 cycle_id INTEGER REFERENCES cycles(cycle_id) ON UPDATE CASCADE,
 beamline_id INTEGER REFERENCES beamlines(beamline_id) ON UPDATE CASCADE,
 btr_id INTEGER REFERENCES btrs(btr_id) ON UPDATE CASCADE,
 sample_id INTEGER REFERENCES sample(sample_id) ON UPDATE CASCADE,
 tstamp INTEGER NOT NULL UNIQUE
);

CREATE TABLE files (
 file_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
 dataset_id BIGINT REFERENCES datasets(dataset_id) ON UPDATE CASCADE,
 name VARCHAR(100) NOT NULL
);
