--https://stackoverflow.com/questions/18387209/sqlite-syntax-for-creating-table-with-foreign-key

CREATE TABLE PROCESSING (
    PROCESSING_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROCESSING VARCHAR(700) NOT NULL UNIQUE,
    CREATE_AT INTEGER,
    CREATE_BY VARCHAR(500),
    MODIFY_AT INTEGER,
    MODIFY_BY VARCHAR(500)
);
CREATE TABLE PARENTS (
    PARENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PARENT VARCHAR(700) NOT NULL UNIQUE,
    CREATE_AT INTEGER,
    CREATE_BY VARCHAR(500),
    MODIFY_AT INTEGER,
    MODIFY_BY VARCHAR(500)
);
CREATE TABLE SITES (
    SITE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SITE VARCHAR(700) NOT NULL UNIQUE,
    CREATE_AT INTEGER,
    CREATE_BY VARCHAR(500),
    MODIFY_AT INTEGER,
    MODIFY_BY VARCHAR(500)
);
CREATE TABLE BUCKETS (
    BUCKET_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BUCKET VARCHAR(700) NOT NULL UNIQUE,
    META_ID VARCHAR(700),
    DATASET_ID INTEGER REFERENCES DATASETS(DATASET_ID) ON UPDATE CASCADE,
    CREATE_AT INTEGER,
    CREATE_BY VARCHAR(500),
    MODIFY_AT INTEGER,
    MODIFY_BY VARCHAR(500)
);
CREATE TABLE METADATA (
    META_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DID VARCHAR(700) NOT NULL UNIQUE,
    CREATE_AT INTEGER,
    CREATE_BY VARCHAR(500),
    MODIFY_AT INTEGER,
    MODIFY_BY VARCHAR(500)
);
CREATE TABLE DATASETS (
    DATASET_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DATASET VARCHAR(700) NOT NULL UNIQUE,
    META_ID INTEGER REFERENCES METADATA(META_ID) ON UPDATE CASCADE,
    SITE_ID INTEGER REFERENCES SITES(SITE_ID) ON UPDATE CASCADE,
    PROCESSING_ID INTEGER REFERENCES PROCESSINGS(PROCESSING_ID) ON UPDATE CASCADE,
    PARENT_ID INTEGER REFERENCES PARENTS(PARENT_ID) ON UPDATE CASCADE,
    CREATE_AT INTEGER,
    CREATE_BY VARCHAR(500),
    MODIFY_AT INTEGER,
    MODIFY_BY VARCHAR(500)
);
CREATE TABLE FILES (
    FILE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FILE VARCHAR(700) NOT NULL UNIQUE,
    IS_FILE_VALID INTEGER DEFAULT 1,
    META_ID INTEGER REFERENCES METADATA(META_ID) ON UPDATE CASCADE,
    DATASET_ID INTEGER REFERENCES DATASETS(DATASET_ID) ON UPDATE CASCADE,
    CREATE_AT INTEGER,
    CREATE_BY VARCHAR(500),
    MODIFY_AT INTEGER,
    MODIFY_BY VARCHAR(500)
);
