package main

// ID3A schema
type ID3A struct {
	Facility                       string    `json:"Facility"`
	Cycle                          string    `json:"Cycle"`
	PI                             string    `json:"PI"`
	BTR                            string    `json:"BTR"`
	Experiments                    string    `json:"Experiments"`
	Beamline                       []string  `json:"Beamline"`
	StaffScientist                 []string  `json:"StaffScientist"`
	BeamlineFundingPartner         []string  `json:"BeamlineFundingPartner"`
	Affiliation                    []string  `json:"Affiliation"`
	Alignment                      bool      `json:"Alignment"`
	EnergyScan                     bool      `json:"EnergyScan"`
	UndulatorScan                  bool      `json:"UndulatorScan"`
	BeamSlitHorizontalSize         float64   `json:"BeamSlitHorizontalSize"`
	BeamSlitVerticalSize           float64   `json:"BeamSlitVerticalSize"`
	BeamSlitHorizontalPosition     float64   `json:"BeamSlitHorizontalPosition"`
	BeamSlitVerticalPosition       float64   `json:"BeamSlitVerticalPosition"`
	PreSlitHorizontalSize          float64   `json:"PreSlitHorizontalSize"`
	PreSlitVerticalSize            float64   `json:"PreSlitVerticalSize"`
	PreSlitHorizontalPosition      float64   `json:"PreSlitHorizontalPosition"`
	PreSlitVerticalPosition        float64   `json:"PreSlitVerticalPosition"`
	GuardSlitHorizontalSize        float64   `json:"GuardSlitHorizontalSize"`
	GuardSlitVerticalSize          float64   `json:"GuardSlitVerticalSize"`
	GuardSlitHorizontalPosition    float64   `json:"GuardSlitHorizontalPosition"`
	GuardSlitVerticalPosition      float64   `json:"GuardSlitVerticalPosition"`
	DataLocationRaw                string    `json:"DataLocationRaw"`
	DataLocationMeta               string    `json:"DataLocationMeta"`
	DataLocationReduced            string    `json:"DataLocationReduced"`
	DataLocationScratch            string    `json:"DataLocationScratch"`
	DataLocationBeamtimeNotes      string    `json:"DataLocationBeamtimeNotes"`
	CESRConditions                 []string  `json:"CESRConditions"`
	BeamEnergy                     float64   `json:"BeamEnergy"`
	Monochromator                  []string  `json:"Monochromator"`
	Focusing                       []string  `json:"Focusing"`
	AttenMaterial                  []string  `json:"AttenMaterial"`
	AttenThickness                 float64   `json:"AttenThickness"`
	EnergyFoil                     []string  `json:"EnergyFoil"`
	Detectors                      []string  `json:"Detectors"`
	ExperimentType                 []string  `json:"ExperimentType"`
	Technique                      []string  `json:"Technique"`
	InSitu                         bool      `json:"InSitu"`
	MechanicalTest                 bool      `json:"MechanicalTest"`
	MechanicalTestType             []string  `json:"MechanicalTestType"`
	MechanicalLoadFrame            []string  `json:"MechanicalLoadFrame"`
	MechanicalGrips                []string  `json:"MechanicalGrips"`
	SupplementaryTechnique         []string  `json:"SupplementaryTechnique"`
	Furnace                        []string  `json:"Furnace"`
	Processing                     []string  `json:"Processing"`
	Calibration                    bool      `json:"Calibration"`
	ReferenceCalibrantSampleName   string    `json:"ReferenceCalibrantSampleName"`
	ReferenceCalibrantScanNumber   int32     `json:"ReferenceCalibrantScanNumber"`
	ReferenceEnergyScanSampleName  string    `json:"ReferenceEnergyScanSampleName"`
	ReferenceEnergyScanNumber      int32     `json:"ReferenceEnergyScanNumber"`
	SampleName                     string    `json:"SampleName"`
	SampleCommonName               string    `json:"SampleCommonName"`
	SampleChemicalFormula          string    `json:"SampleChemicalFormula"`
	SampleUnitCell                 []float64 `json:"SampleUnitCell"`
	SampleSpaceGroup               int64     `json:"SampleSpaceGroup"`
	SampleGeometry                 string    `json:"SampleGeometry"`
	SampleMatPedHeatTreatment      string    `json:"SampleMatPedHeatTreatment"`
	SampleMatPedProcessingRoute    string    `json:"SampleMatPedProcessingRoute"`
	MaterialSafetyHazardousSamples bool      `json:"MaterialSafetyHazardousSamples"`
}

// ID4B schema definition
type ID4B struct {
	Facility                       string   `json:"Facility"`
	Cycle                          string   `json:"Cycle"`
	PI                             string   `json:"PI"`
	BTR                            string   `json:"BTR"`
	Experiments                    string   `json:"Experiments"`
	Beamline                       []string `json:"Beamline"`
	StaffScientist                 []string `json:"StaffScientist"`
	BeamlineFundingPartner         []string `json:"BeamlineFundingPartner"`
	Alignment                      bool     `json:"Alignment"`
	EnergyScan                     bool     `json:"EnergyScan"`
	UndulatorScan                  bool     `json:"UndulatorScan"`
	SpotSize                       string   `json:"SpotSize"`
	DataLocationRaw                string   `json:"DataLocationRaw"`
	DataLocationMeta               string   `json:"DataLocationMeta"`
	DataLocationReduced            string   `json:"DataLocationReduced"`
	DataLocationBeamtimeNotes      string   `json:"DataLocationBeamtimeNotes"`
	DataLocationScientificData     string   `json:"DataLocationScientificData"`
	CESRConditions                 []string `json:"CESRConditions"`
	BeamEnergy                     string   `json:"BeamEnergy"`
	InsertionDevice                []string `json:"InsertionDevice"`
	Monochromator                  []string `json:"Monochromator"`
	EnergyFoil                     []string `json:"EnergyFoil"`
	Detectors                      []string `json:"Detectors"`
	ExperimentType                 []string `json:"ExperimentType"`
	InSitu                         bool     `json:"InSitu"`
	Technique                      []string `json:"Technique"`
	CryoCooler                     []string `json:"CryoCooler"`
	Cryostream11Kto500K            string   `json:"Cryostream11Kto500K"`
	Cryostat3Kto300K               string   `json:"Cryostat3Kto300K"`
	ScanEdgeK                      string   `json:"ScanEdgeK"`
	ScanEdgeL                      string   `json:"ScanEdgeL"`
	Calibration                    []string `json:"Calibration"`
	ReferenceCalibrantSampleName   string   `json:"ReferenceCalibrantSampleName"`
	SampleType                     []string `json:"SampleType"`
	SampleName                     string   `json:"SampleName"`
	SampleChemicalFormula          string   `json:"SampleChemicalFormula"`
	SampleThermalGradient          bool     `json:"SampleThermalGradient"`
	SampleUnitCell                 string   `json:"SampleUnitCell"`
	SampleDSpacing                 float64  `json:"SampleDSpacing"`
	SampleMass                     string   `json:"SampleMass"`
	SampleSpaceGroup               string   `json:"SampleSpaceGroup"`
	SampleMatPedHeatTreatment      string   `json:"SampleMatPedHeatTreatment"`
	SampleMatPedProcessingRoute    string   `json:"SampleMatPedProcessingRoute"`
	SampleState                    []string `json:"SampleState"`
	SamplePreparationDate          string   `json:"SamplePreparationDate"`
	MaterialSafetyHazardousSamples bool     `json:"MaterialSafetyHazardousSamples"`
	HolderLabel                    string   `json:"HolderLabel"`
}

// ID1A3 schema definition
type ID1A3 struct {
	Facility                       string   `json:"Facility"`
	Cycle                          string   `json:"Cycle"`
	PI                             string   `json:"PI"`
	BTR                            string   `json:"BTR"`
	Experiments                    string   `json:"Experiments"`
	Beamline                       []string `json:"Beamline"`
	StaffScientist                 []string `json:"StaffScientist"`
	BeamlineFundingPartner         []string `json:"BeamlineFundingPartner"`
	Affiliation                    []string `json:"Affiliation"`
	Alignment                      bool     `json:"Alignment"`
	EnergyScan                     bool     `json:"EnergyScan"`
	EnergyScanDocument             string   `json:"EnergyScanDocument"`
	DataLocationRaw                string   `json:"DataLocationRaw"`
	DataLocationMeta               string   `json:"DataLocationMeta"`
	DataLocationReduced            string   `json:"DataLocationReduced"`
	DataLocationBeamtimeNotes      string   `json:"DataLocationBeamtimeNotes"`
	CESRConditions                 []string `json:"CESRConditions"`
	InsertionDevice                []string `json:"InsertionDevice"`
	Monochromator                  []string `json:"Monochromator"`
	Focusing                       []string `json:"Focusing"`
	BeamMode                       []string `json:"BeamMode"`
	BeamEnergy                     float64  `json:"BeamEnergy"`
	BeamlineSetupDocument          string   `json:"BeamlineSetupDocument"`
	Detectors                      []string `json:"Detectors"`
	ExperimentType                 []string `json:"ExperimentType"`
	Technique                      []string `json:"Technique"`
	InSitu                         bool     `json:"InSitu"`
	MechanicalTest                 bool     `json:"MechanicalTest"`
	MechanicalTestType             []string `json:"MechanicalTestType"`
	MechanicalLoadFrame            []string `json:"MechanicalLoadFrame"`
	MechanicalGrips                []string `json:"MechanicalGrips"`
	SupplementaryTechnique         []string `json:"SupplementaryTechnique"`
	Furnace                        []string `json:"Furnace"`
	SampleName                     string   `json:"SampleName"`
	Calibration                    bool     `json:"Calibration"`
	SampleSpaceGroup               string   `json:"SampleSpaceGroup"`
	SampleGeometry                 string   `json:"SampleGeometry"`
	SampleMatPedHeatTreatment      string   `json:"SampleMatPedHeatTreatment"`
	SampleMatPedProcessingRoute    string   `json:"SampleMatPedProcessingRoute"`
	MaterialSafetyHazardousSamples bool     `json:"MaterialSafetyHazardousSamples"`
	SampleState                    []string `json:"SampleState"`
}

// Common schema definition
type Common struct {
	Facility                  string   `json:"Facility"`
	Cycle                     string   `json:"Cycle"`
	PI                        string   `json:"PI"`
	BTR                       string   `json:"BTR"`
	Experiments               string   `json:"Experiments"`
	Beamline                  []string `json:"Beamline"`
	StaffScientist            []string `json:"StaffScientist"`
	BeamlineFundingPartner    []string `json:"BeamlineFundingPartner"`
	Alignment                 bool     `json:"Alignment"`
	DataLocationRaw           string   `json:"DataLocationRaw"`
	Detectors                 []string `json:"Detectors"`
	CESRConditions            []string `json:"CESRConditions"`
	ExperimentType            []string `json:"ExperimentType"`
	Technique                 []string `json:"Technique"`
	SampleType                []string `json:"SampleType"`
	SampleName                string   `json:"SampleName"`
	Calibration               bool     `json:"Calibration"`
	DataLocationMeta          string   `json:"DataLocationMeta"`
	DataLocationReduced       string   `json:"DataLocationReduced"`
	DataLocationScratch       string   `json:"DataLocationScratch"`
	DataLocationBeamtimeNotes string   `json:"DataLocationBeamtimeNotes"`
}

// Lite schema definition
type Lite struct {
	Facility                  string   `json:"Facility"`
	Cycle                     string   `json:"Cycle"`
	PI                        string   `json:"PI"`
	BTR                       string   `json:"BTR"`
	Experiments               string   `json:"Experiments"`
	Beamline                  []string `json:"Beamline"`
	StaffScientist            []string `json:"StaffScientist"`
	BeamlineFundingPartner    []string `json:"BeamlineFundingPartner"`
	Affiliation               []string `json:"Affiliation"`
	Alignment                 bool     `json:"Alignment"`
	DataLocationRaw           string   `json:"DataLocationRaw"`
	Detectors                 []string `json:"Detectors"`
	CESRConditions            []string `json:"CESRConditions"`
	ExperimentType            []string `json:"ExperimentType"`
	Technique                 []string `json:"Technique"`
	SampleType                []string `json:"SampleType"`
	SampleName                string   `json:"SampleName"`
	Calibration               bool     `json:"Calibration"`
	DataLocationMeta          string   `json:"DataLocationMeta"`
	DataLocationReduced       string   `json:"DataLocationReduced"`
	DataLocationScratch       string   `json:"DataLocationScratch"`
	DataLocationBeamtimeNotes string   `json:"DataLocationBeamtimeNotes"`
}
